# Generated by Django 4.2.1 on 2023-06-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cust', '0002_customers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='image',
            new_name='userimage',
        ),
    ]
