# Generated by Django 4.2.1 on 2023-06-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cust', '0003_rename_image_customers_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='userimage',
        ),
    ]
