# Generated by Django 4.2.1 on 2023-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cust', '0006_products_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='shipping_price',
            new_name='discounted_price',
        ),
    ]
